# Generated by Django 6.0.6 on 2026-10-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('aggregate_id', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('published_at__isnull', True)), fields=['id'], name='outbox_unpublished_idx')],
            },
        ),
    ]
