# Generated by Django 6.0.6 on 2026-06-09 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.SlugField(help_text='Twój unikalny link: coachly.com/twoja_nazwa', unique=True, verbose_name='Nazwa użytkownika (unikalna URL)')),
                ('full_name', models.CharField(max_length=255, verbose_name='Imię i nazwisko')),
                ('sport', models.CharField(max_length=100, verbose_name='Dyscyplina')),
                ('location', models.CharField(max_length=255, verbose_name='Lokalizacja zajęć')),
                ('headline', models.CharField(max_length=255, verbose_name='Header (Nagłówek profilu)')),
                ('description', models.TextField(verbose_name='Opis')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Stawka godzinowa (PLN)')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email kontaktowy')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Nr telefonu kontaktowy')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='trainer_pics/', verbose_name='Zdjęcie profilowe')),
                ('tiktok', models.URLField(blank=True, null=True, verbose_name='TikTok')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
