# Generated by Django 6.0.6 on 2026-06-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_trainerprofileupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='classes_description',
            field=models.TextField(blank=True, help_text='Opisz, jak wyglądają Twoje zajęcia', null=True, verbose_name='Opis zajęć'),
        ),
        migrations.AddField(
            model_name='trainerprofileupdate',
            name='classes_description',
            field=models.TextField(blank=True, help_text='Opisz, jak wyglądają Twoje zajęcia', null=True, verbose_name='Opis zajęć'),
        ),
    ]
