# Generated by Django 6.0.6 on 2026-06-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_trainerprofile_classes_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='contact_phone',
            field=models.CharField(max_length=20, verbose_name='Telefon kontaktowy'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook (opcjonalnie)'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram (opcjonalnie)'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Zdjęcie profilowe'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='sport',
            field=models.CharField(help_text='Np. Joga, Boks, Trening personalny', max_length=255, verbose_name='Dyscypliny (oddziel przecinkami)'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='tiktok',
            field=models.URLField(blank=True, null=True, verbose_name='TikTok (opcjonalnie)'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='username',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Nazwa użytkownika (URL)'),
        ),
        migrations.AlterField(
            model_name='trainerprofileupdate',
            name='sport',
            field=models.CharField(help_text='Np. Joga, Boks, Trening personalny', max_length=255, verbose_name='Dyscypliny (oddziel przecinkami)'),
        ),
    ]
