# Generated by Django 6.0.6 on 2026-06-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0006_trainerprofile_training_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='trainerprofileupdate',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Imię'),
        ),
    ]
