# Generated by Django 6.0.6 on 2026-06-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0007_alter_trainerprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon kontaktowy'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='username',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Nazwa użytkownika (będzie w URL profilu)'),
        ),
        migrations.AlterField(
            model_name='trainerprofileupdate',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nr telefonu kontaktowy'),
        ),
    ]
