# Generated by Django 6.0.6 on 2026-06-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_trainer',
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Zarejestrowany'), ('PENDING_APPLICATION', 'Złożono wniosek'), ('APPROVED_TRAINER', 'Trener')], default='REGISTERED', max_length=30, verbose_name='Status konta'),
        ),
    ]
