# Generated by Django 6.0.6 on 2026-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_sport_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Zarejestrowany'), ('PENDING_APPLICATION', 'Złożono wniosek'), ('APPROVED_TRAINER', 'Trener'), ('BANNED', 'Zbanowany'), ('ADMIN', 'Administrator')], default='REGISTERED', max_length=30, verbose_name='Status konta'),
        ),
    ]
