# Generated by Django 6.0.6 on 2026-07-02 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_status'),
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Konto Google',
                'verbose_name_plural': 'Accounts registered via Google',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('socialaccount.socialaccount',),
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Normal accounts', 'verbose_name_plural': 'Accounts registered normally'},
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nazwisko')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil klienta',
                'verbose_name_plural': 'Profile klientów',
            },
        ),
    ]
