"""Add chat rooms

Revision ID: ffe36434309f
Revises: 654a43c4a3c6
Create Date: 2026-07-02 14:59:55.081319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffe36434309f'
down_revision: Union[str, Sequence[str], None] = '654a43c4a3c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'trainer_id', name='uq_client_trainer_room')
    )
    op.create_index(op.f('ix_chat_rooms_client_id'), 'chat_rooms', ['client_id'], unique=False)
    op.create_index(op.f('ix_chat_rooms_id'), 'chat_rooms', ['id'], unique=False)
    op.create_index(op.f('ix_chat_rooms_trainer_id'), 'chat_rooms', ['trainer_id'], unique=False)
    op.add_column('chat_messages', sa.Column('room_id', sa.Integer(), nullable=False))
    op.add_column('chat_messages', sa.Column('sender_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_room_id'), 'chat_messages', ['room_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_sender_id'), 'chat_messages', ['sender_id'], unique=False)
    op.create_foreign_key(None, 'chat_messages', 'chat_rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_messages', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_index(op.f('ix_chat_messages_sender_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_room_id'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.drop_column('chat_messages', 'sender_id')
    op.drop_column('chat_messages', 'room_id')
    op.drop_index(op.f('ix_chat_rooms_trainer_id'), table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_id'), table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_client_id'), table_name='chat_rooms')
    op.drop_table('chat_rooms')
    # ### end Alembic commands ###
