# Generated by Django 6.0.6 on 2026-06-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_is_trainer_customuser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='sport',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
