# Generated by Django 6.0.6 on 2026-06-09 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerProfileUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Imię i nazwisko')),
                ('sport', models.CharField(max_length=100, verbose_name='Dyscyplina')),
                ('location', models.CharField(max_length=255, verbose_name='Lokalizacja zajęć')),
                ('headline', models.CharField(max_length=255, verbose_name='Krótki nagłówek profilu (np. Trener Personalny)')),
                ('description', models.TextField(verbose_name='Opis')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Stawka godzinowa (PLN)')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='E-mail kontaktowy')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Nr telefonu kontaktowy')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='pending_profile_pics/', verbose_name='Zdjęcie profilowe')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram (opcjonalnie)')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook (opcjonalnie)')),
                ('tiktok', models.URLField(blank=True, null=True, verbose_name='TikTok (opcjonalnie)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_update', to='trainers.trainerprofile')),
            ],
        ),
    ]
