# Generated by Django 6.0.6 on 2026-06-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0004_alter_trainerprofile_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Chłopak'), ('F', 'Dziewczyna')], max_length=1, null=True, verbose_name='Płeć'),
        ),
        migrations.AddField(
            model_name='trainerprofileupdate',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Chłopak'), ('F', 'Dziewczyna')], max_length=1, null=True, verbose_name='Płeć'),
        ),
    ]
