# Generated by Django 6.0.6 on 2026-06-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0005_trainerprofile_gender_trainerprofileupdate_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='training_type',
            field=models.CharField(choices=[('STATIONARY', 'Stacjonarnie'), ('ONLINE', 'Online'), ('BOTH', 'Online & Stacjonarnie')], default='STATIONARY', max_length=15, verbose_name='Typ zajęć'),
        ),
        migrations.AddField(
            model_name='trainerprofileupdate',
            name='training_type',
            field=models.CharField(choices=[('STATIONARY', 'Stacjonarnie'), ('ONLINE', 'Online'), ('BOTH', 'Online & Stacjonarnie')], default='STATIONARY', max_length=15, verbose_name='Typ zajęć'),
        ),
    ]
