# Generated by Django 6.0.6 on 2026-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0008_alter_trainerprofile_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon kontaktowy (opcjonalnie)'),
        ),
    ]
