# Generated by Django 6.0.6 on 2026-06-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0010_trainerpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug (URL)'),
        ),
    ]
