# Generated by Django 6.0.6 on 2026-06-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0011_alter_trainerpost_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa sportu')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Dyscyplina sportowa',
                'verbose_name_plural': 'Dyscypliny sportowe',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='sport',
            field=models.CharField(blank=True, help_text='Np. Joga, Boks, Trening personalny', max_length=255, verbose_name='Dyscypliny (STARE POLE)'),
        ),
        migrations.AlterField(
            model_name='trainerprofileupdate',
            name='sport',
            field=models.CharField(blank=True, help_text='Np. Joga, Boks, Trening personalny', max_length=255, verbose_name='Dyscypliny (STARE POLE)'),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='trainers', to='trainers.sport', verbose_name='Dyscypliny'),
        ),
        migrations.AddField(
            model_name='trainerprofileupdate',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='profile_updates', to='trainers.sport', verbose_name='Dyscypliny'),
        ),
    ]
