# Generated by Django 6.0.6 on 2026-06-25 19:42

from django.db import migrations

def migrate_sports(apps, schema_editor):
    TrainerProfile = apps.get_model('trainers', 'TrainerProfile')
    TrainerProfileUpdate = apps.get_model('trainers', 'TrainerProfileUpdate')
    Sport = apps.get_model('trainers', 'Sport')
    from django.utils.text import slugify

    # Migrate TrainerProfile
    for profile in TrainerProfile.objects.all():
        if profile.sport:
            sport_names = [s.strip() for s in profile.sport.split(',') if s.strip()]
            for name in sport_names:
                sport_obj, created = Sport.objects.get_or_create(
                    name=name, 
                    defaults={'slug': slugify(name)}
                )
                profile.sports.add(sport_obj)

    # Migrate TrainerProfileUpdate
    for update in TrainerProfileUpdate.objects.all():
        if update.sport:
            sport_names = [s.strip() for s in update.sport.split(',') if s.strip()]
            for name in sport_names:
                sport_obj, created = Sport.objects.get_or_create(
                    name=name, 
                    defaults={'slug': slugify(name)}
                )
                update.sports.add(sport_obj)


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0012_sport_alter_trainerprofile_sport_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_sports),
    ]
