# Generated by Django 6.0.6 on 2026-06-25 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0013_auto_20260625_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerprofile',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='trainerprofileupdate',
            name='sport',
        ),
    ]
