# Generated by Django 6.0.6 on 2026-07-02 17:03

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0014_remove_trainerprofile_sport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='trainerpost',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='title', unique=True, verbose_name='Slug (URL)'),
        ),
    ]
