# Generated by Django 6.0.6 on 2026-07-09 08:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0015_alter_sport_slug_alter_trainerpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=5, verbose_name='Tagi (np. sport, granie, max 5)'),
        ),
        migrations.AddField(
            model_name='trainerprofileupdate',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=5, verbose_name='Tagi (np. sport, granie, max 5)'),
        ),
    ]
