# Generated by Django 6.0.6 on 2026-10-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0017_sanitize_existing_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='contact_email',
            field=models.EmailField(max_length=254, verbose_name='E-mail kontaktowy'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='headline',
            field=models.CharField(max_length=255, verbose_name='Krótki nagłówek profilu (np. Trener Personalny)'),
        ),
        migrations.AlterField(
            model_name='trainerprofileupdate',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon kontaktowy (opcjonalnie)'),
        ),
        migrations.AlterField(
            model_name='trainerprofileupdate',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Stawka godzinowa (PLN)'),
        ),
    ]
